spring:
    profiles:
        active:
        - dev
---
spring:
    profiles: dev   # 开发环境
    application:
        name: microservicecloud-config-wanjiang-dev
---
spring:
    profiles: test  # 测试环境
    application:
        name: microservicecloud-config-wanjiang-test

# 请以 UTF-8 格式保存